"""Constants for the servodrive integration."""

DOMAIN = "servodrive"

CONF_BRIDGE_ID = "bridge_id"

SERVODRIVE_MANUFACTURER = "JBGmbH"
SERVODRIVE_MODEL_PREFIX = "SERVO-DRIVE"
SERVIDRIVE_BRIDGE_NAME = "SDSBridge"
SERVIDRIVE_BRIDGE_MODEL = ""

SERVODRIVE_FLAP = "flap"
SERVODRIVE_DRAWER = "drawer"
SERVODRIVE_LOCK = "lock"
